controllers:
    resource: ../src/Controller/
    type: attribute

app_upload:
    path: /upload
    controller: App\Controller\TraitementController::uploadFichier
    methods: [POST]

app_liste_fichiers:
    path: /liste-fichiers
    controller: App\Controller\TraitementController::listeFichiers
    methods: [GET]

app_liste_operations:
    path: /liste-operations
    controller: App\Controller\TraitementController::listeOperations
    methods: [GET]

app_liste_operations_login:
    path: /liste-operations/{login}
    controller: App\Controller\TraitementController::listeOperationsLogin
    methods: [GET]


app_fichier:
    path: /fichier/{id}
    controller: App\Controller\TraitementController::afficherFichier
    methods: [GET]

app_supprimer_fichier:
    path: '/fichier/del/{id}'
    controller: 'App\Controller\TraitementController::supprimerFichier'
    methods: [DELETE]
