framework:
    messenger:
        transports:
            async:
                dsn: 'in-memory://'
                options:
                    queue_name: async
        routing:
            'App\Message\TraitementFichierMessage': async